name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  firefox:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Firefox
        uses: ./ # if copying, replace with cypress-io/github-action@v7
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: screenshots-in-firefox
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser
